workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        CERTIFICATE_PRIVATE_KEY_FILE: $signing.CERTIFICATE_PRIVATE_KEY_FILE
        PROVISIONING_PROFILE: $signing.PROVISIONING_PROFILE
        CERTIFICATE_PRIVATE_KEY_PASSWORD: $signing.CERTIFICATE_PRIVATE_KEY_PASSWORD
    scripts:
      - name: Prepare iOS Certificate and Provisioning Profile
        script: |
          echo "Preparing iOS certificate and provisioning profile..."
          mkdir -p ~/build
          echo $CERTIFICATE_PRIVATE_KEY_FILE | base64 --decode > ~/build/cert.p12
          echo $PROVISIONING_PROFILE | base64 --decode > ~/build/profile.mobileprovision

          security create-keychain -p "" build.keychain
          security import ~/build/cert.p12 -t agg -k ~/build/build.keychain -P $CERTIFICATE_PRIVATE_KEY_PASSWORD -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/build/build.keychain
          security list-keychains -d user -s ~/build/build.keychain
          security default-keychain -s ~/build/build.keychain

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ~/build/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

          echo "Certificate and provisioning profile are prepared."

      - name: Install Node.js Dependencies
        script: |
          echo "Installing Node.js dependencies..."
          npm install

      - name: Install CocoaPods Dependencies
        script: |
          echo "Installing CocoaPods dependencies..."
          cd ios
          pod install --repo-update

      - name: Build iOS App
        script: |
          echo "Building iOS app..."
          cd ios
          set -o pipefail && xcodebuild -workspace realspace3.xcworkspace -scheme realspace3 -configuration Release -allowProvisioningUpdates archive -archivePath ~/build/realspace3.xcarchive | tee build.log | xcpretty
          if [ ! -d ~/build/realspace3.xcarchive ]; then
            echo "Archive not found!"
            cat build.log
            exit 1
          fi

          echo "Exporting IPA..."
          xcodebuild -exportArchive -archivePath ~/build/realspace3.xcarchive -exportPath ~/build -exportOptionsPlist ExportOptions.plist | tee export.log | xcpretty
          if [ ! -f ~/build/realspace3.ipa ]; then
            echo "IPA file not found!"
            cat export.log
            exit 1
          fi

          ls -l ~/build

    artifacts:
      - ~/build/*.ipa
