workflows:
  ios:
    name: iOS Build
    max_build_duration: 100
    environment:
      vars:
        CERTIFICATE_PRIVATE_KEY_FILE: $signing.CERTIFICATE_PRIVATE_KEY_FILE
        PROVISIONING_PROFILE_BASE64: $signing.PROVISIONING_PROFILE # Variável Base64
        CERTIFICATE_PRIVATE_KEY_PASSWORD: $signing.CERTIFICATE_PRIVATE_KEY_PASSWORD
        DEVELOPMENT_TEAM: 375WVRSY2Q
        CODE_SIGN_STYLE: "Manual"
        CODE_SIGN_IDENTITY: "Apple Development"
      xcode: 15.4
      cocoapods: default
      node: 18.16.0
      npm: 9.8.1
      ruby: 3.0.4
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Install Dependencies
        script: npm install
      - name: Install CocoaPods
        script: gem install cocoapods
      - name: Install Pods
        script: cd ios && pod install && cd ..
      - name: Bundle React Native assets
        script: npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
            - name: Save Base64 Content
        script: |
          # Verifica se a variável PROVISIONING_PROFILE_BASE64 está definida e não vazia
          if [ -z "$PROVISIONING_PROFILE_BASE64" ]; then
            echo "Error: PROVISIONING_PROFILE_BASE64 is not set or is empty."
            exit 1
          fi
          
          # Salva o conteúdo da variável em um arquivo
          echo "$PROVISIONING_PROFILE_BASE64" > $CM_BUILD_DIR/ios/provisioning_profile_base64.txt
          
          # Verifica se o arquivo foi criado e não está vazio
          if [ ! -s "$CM_BUILD_DIR/ios/provisioning_profile_base64.txt" ]; then
            echo "Error: provisioning_profile_base64.txt is not created or is empty."
            exit 1
          fi

          # Decodifica o arquivo base64 para .mobileprovision
          if ! base64 --decode $CM_BUILD_DIR/ios/provisioning_profile_base64.txt > $CM_BUILD_DIR/ios/YourProfile.mobileprovision; then
            echo "Error: Failed to decode base64 content."
            exit 1
          fi
          
          # Verifica se o arquivo .mobileprovision foi criado e não está vazio
          if [ ! -s "$CM_BUILD_DIR/ios/YourProfile.mobileprovision" ]; then
            echo "Error: YourProfile.mobileprovision is not created or is empty."
            exit 1
          fi
      - name: Verify Provisioning Profile
        script: |
          if [ ! -f "$CM_BUILD_DIR/ios/YourProfile.mobileprovision" ]; then
            echo "Error: Provisioning profile not found."
            exit 1
          fi
      - name: Build iOS app
        script: |
          xcodebuild -workspace ios/realspace3.xcworkspace \
          -scheme realspace3 \
          -configuration Release \
          -sdk iphoneos \
          -archivePath $CM_BUILD_DIR/ios/realspace3.xcarchive \
          clean archive \
          CODE_SIGN_STYLE="$CODE_SIGN_STYLE" \
          CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
          DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
          PROVISIONING_PROFILE="$CM_BUILD_DIR/ios/YourProfile.mobileprovision"
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - jg.neiva@gmail.com
