workflows:
  ios:
    name: iOS Build
    max_build_duration: 100
    environment:
      groups:
        - signing
      vars:
        CERTIFICATE_PRIVATE_KEY_FILE: $CERTIFICATE_PRIVATE_KEY_FILE
        CERTIFICATE_PRIVATE_KEY_PASSWORD: $CERTIFICATE_PRIVATE_KEY_PASSWORD
        DEVELOPMENT_TEAM: 375WVRSY2Q
        CODE_SIGN_STYLE: "Manual"
        CODE_SIGN_IDENTITY: "Apple Development"
      xcode: 15.4
      cocoapods: default
      node: 18.16.0
      npm: 9.8.1
      ruby: 3.0.4
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/node_modules
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Install Dependencies
        script: npm install
      - name: Install CocoaPods
        script: gem install cocoapods
      - name: Install Pods
        script: cd ios && pod install && cd ..
      - name: Bundle React Native assets
        script: npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
      - name: Save Base64 Content
        script: |
          # Ensure the Base64 content is properly formatted
          provisioning_profile_base64="MII//gYJKoZIhvcNAQcCoII/7zCCP+sCAQExCzAJBgUrDgMCGgUAMIIwCwYJKoZIhvcNAQcBoIIv/ASCL/g8P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJVVEYtOCI/Pgo8IURPQ1RZUEUgcGxpc3QgUFVCTElDICItLy9BcHBsZS8vRFREIFBMSVNUIDEuMC8vRU4iICJodHRwOi8vd3d3LmFwcGxlLmNvbS9EVERzL1Byb3BlcnR5TGlzdC0xLjAuZHRkIj4KPHBsaXN0IHZlcnNpb249IjEuMCI+CjxkaWN0PgoJPGtleT5BcHBJRE5hbWU8L2tleT4KCTxzdHJpbmc+UmVhbHNwYWNlPC9zdHJpbmc+Cgk8a2V5PkFwcGxpY2F0aW9uSWRlbnRpZmllclByZWZpeDwva2V5PgoJPGFycmF5PgoJPHN0cmluZz4zNzVXVlJSWTJRPC9zdHJpbmc+Cgk8L2FycmF5PgoJPGtleT5DcmVhdGlvbkRhdGU8L2tleT4KCTxkYXRlPjIwMjQtMDgtMDlUMjM6MzA6NDlaPC9kYXRlPgoJPGtleT5QbGF0Zm9ybTwva2V5PgoJPGFycmF5PgoJCTxzdHJpbmc+aU9TPC9zdHJpbmc+CgkJPHN0cmluZz54ck9TPC9zdHJpbmc+CgkJPHN0cmluZz52aXNpb25PUzwvc3RyaW5nPgoJPC9hcnJheT4KCTxrZXk+SXNYY29kZU1hbmFnZWQ8L2tleT4KCTxmYWxzZS8+Cgk8a2V5PkRldmVsb3BlckNlcnRpZmljYXRlczwva2V5PgoJPGFycmF5PgoJCTxkYXRhPk1JSUZyakNDQkphZ0F3SUJBZ0lRQmh0S2VlWDREQ3NhVDM2LzJWaVp5VEFOQmdrcWhraUc5dzBCQVFzRkFEQjFNVVF3UWdZRFZRUURERHRCY0hCc1pTQlhiM0pzWkhkcFpHVWdSR1YyWld4dmNHVnlJRkpsYkdGMGFXOXVjeUJEWlhKMGFXWnBZMkYwYVc5dUlFRjFkR2h2Y21sMGVURUxNQWtHQTFVRUN3d0NSek14RXpBUkJnTlZCQW9NQ2tGd2NHeGxJRWx1WXk0eEN6QUpCZ05WQkFZVEFsVlRNQjRYRFRJME1EZ3dOREEzTlRBeE5Gb1hEVEkxTURnd05EQTNOVEF4TTFvd2dZa3hHakFZQmdvSmtpYUprL0lzWkFFQkRBb3pNek0xTXpaYU1qVlJNVE13TVFZRFZRUUREQ3BwVUdodmJtVWdSR1YyWld4dmNHVnlPaUJLYjhPamJ5QlRhV3gyWVNBb04wYzBXVmN5VVRVNVV5a3hFekFSQmdOVkJBc01Dak0zTlZkV1VsTlpNbEV4RkRBU0JnTlZCQW9NQzBGbllYUm9iMjRnVEV4RE1Rc3dDUVlEVlFRR0V3SlZVekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLOWJKVGJ2M0VPZUlxSld1K1VTdXhvQjV6VTBRbmFhbmwzRFp2QWZ3UUZEQUZIMWJhNVBrN0x4WEQ1THJvMHV0N3RGS2FxWWNEMGhxSnVweGxRaUo3ZHp2cUl6eTdGbEhPWkE1ajF2Z2FjSGQySnl2R2wwRGFVQnJVVW5vMTBHYy9OUmlPWWRsS2ovZ0ZSMFdsYjhMMHZnVllWeHRZcGp5LzBZakFhdGZpUzNnTFhVS20zN0wxTmhlc3FGSC9TMXdLVG1UKzVoVitxaEswaFJvTnllbmV5RUlFZEtVV0lHV2JkVkRTUW1LVHJFc3ovYnh5TEZnT1AvVy9RUS9qOGxJR1B1dEVORzA0aVltMVVRbnJxaENWMXJ0M082aHpvekpQZFozYWJrUUFqZDU5UFRSTThqT2hGYlZ1VUUvQTh5cUJHQVhIV0lXMm1TaDlKb0RkemxjUGNDQXdFQUFhT0NBaU13Z2dJZk1Bd0dBMVVkRXdFQi93UUNNQUF3SHdZRFZSMGpCQmd3Rm9BVUNmN0FGWkQ1cjJRS2toSzVKaWhqREpmc3A3SXdjQVlJS3dZQkJRVUhBUUVFWkRCaU1DMEdDQ3NHQVFVRkJ6QUNoaUZvZEhSd09pOHZZMlZ5ZEhNdVlYQndiR1V1WTI5dEwzZDNaSEpuTXk1a1pYSXdNUVlJS3dZQkJRVUhNQUdHSldoMGRIQTZMeTl2WTNOd0xtRndjR3hsTG1OdmJTOXZZM053TURNdGQzZGtjbWN6TURNd2dnRWVCZ05WSFNBRWdnRVZNSUlCRVRDQ0FRMEdDU3FHU0liM1kyUUZBVENCL3pDQnd3WUlLd1lCQlFVSEFnSXdnYllNZ2JOU1pXeHBZVzVqWlNCdmJpQjBhR2x6SUdObGNuUnBabWxqWVhSbElHSjVJR0Z1ZVNCd1lYSjBlU0JoYzNOMWJXVnpJR0ZqWTJWd2RHRnVZMlVnY21WdWJteDdzMHVEdUtGOTFSd2RDNXdNbW93R3lKTzNBSG93UUNjWllBb3RQUGxnZ3F2bGRmMUtFZFFnbC94YUE9PQowGgI7JDGAiM5Hrx68DSzY51dkk= # Replace this with your actual Base64 content
          echo "$provisioning_profile_base64" > ~/ios/ProvisioningProfile.mobileprovision
      - name: Build and Archive
        script: |
          xcodebuild -workspace ios/realspace3.xcworkspace -scheme YourScheme -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $CM_BUILD_DIR/realspace3.xcarchive CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="Apple Development" PROVISIONING_PROFILE_SPECIFIER="realspace3"
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/realspace3.xcarchive -exportPath $CM_BUILD_DIR/ipa -exportOptionsPlist ios/exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/realspace3.xcarchive
