workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        CERTIFICATE_PRIVATE_KEY_FILE: $CERTIFICATE_PRIVATE_KEY_FILE
        PROVISIONING_PROFILE: $PROVISIONING_PROFILE
        CERTIFICATE_PRIVATE_KEY_PASSWORD: $CERTIFICATE_PRIVATE_KEY_PASSWORD

    scripts:
      - name: Prepare iOS Certificate and Provisioning Profile
        script: |
          echo "Preparing iOS certificate..."
          echo $CERTIFICATE_PRIVATE_KEY_FILE | base64 --decode > ~/cert.p12
          echo $PROVISIONING_PROFILE | base64 --decode > ~/profile.mobileprovision

      - name: Build iOS App
        script: |
          echo "Building iOS app..."
          # Usando o arquivo .xcodeproj porque não temos um .xcworkspace
          xcodebuild -project ios/realspace3.xcodeproj -scheme realspace3 -configuration Release archive -archivePath ~/build/realspace3.xcarchive
          xcodebuild -exportArchive -archivePath ~/build/realspace3.xcarchive -exportPath ~/build -exportOptionsPlist ios/ExportOptions.plist

    artifacts:
      - build/*.ipa
