workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        CERTIFICATE_PRIVATE_KEY_FILE: $CERTIFICATE_PRIVATE_KEY_FILE
        PROVISIONING_PROFILE: $PROVISIONING_PROFILE
        CERTIFICATE_PRIVATE_KEY_PASSWORD: $CERTIFICATE_PRIVATE_KEY_PASSWORD

    scripts:
      - name: Prepare iOS Certificate and Provisioning Profile
        script: |
          echo "Preparing iOS certificate..."
          mkdir -p ~/build
          echo $CERTIFICATE_PRIVATE_KEY_FILE | base64 --decode > ~/build/cert.p12
          echo $PROVISIONING_PROFILE | base64 --decode > ~/build/profile.mobileprovision
          ls -l ~/build

      - name: Build iOS App
        script: |
          echo "Building iOS app..."
          xcodebuild -project ios/realspace3.xcodeproj -scheme realspace3 -configuration Release archive -archivePath ~/build/realspace3.xcarchive | tee build.log | xcpretty
          if [ ! -d ~/build/realspace3.xcarchive ]; then
            echo "Archive not found!"
            exit 1
          fi
          xcodebuild -exportArchive -archivePath ~/build/realspace3.xcarchive -exportPath ~/build -exportOptionsPlist ios/ExportOptions.plist | tee build.log | xcpretty
          ls -l ~/build  # Verifica se o arquivo IPA foi gerado

    artifacts:
      - ~/build/*.ipa  # Certifique-se de que o caminho do artefato está correto
