import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000066',
  },
  modalView: {
    backgroundColor: '#EEEEEE',
    padding: 20,
    borderRadius: 10,
    width: '80%',
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  modalTitle: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#2D2D2D'
  },
  optionContainer1: {
    position: 'absolute',
    top: '48%',
    left: '67%',
    width: '30%',
    backgroundColor: 'white',
    borderTopWidth: 0.25,
    borderColor: '#C7C8C8',
    paddingHorizontal: 16,
    paddingBottom: 8,
    zIndex: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 6, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 6,
  },
  optionContainer2: {
    position: 'absolute',
    top: '56%',
    left: '67%',
    width: '30%',
    backgroundColor: 'white',
    borderTopWidth: 0.25,
    borderColor: '#C7C8C8',
    paddingHorizontal: 16,
    paddingBottom: 8,
    zIndex: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 6, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 6,
  },
  optionContainer3: {
    position: 'absolute',
    top: '35%',
    left: '67%',
    width: '30%',
    backgroundColor: 'white',
    borderTopWidth: 0.25,
    borderColor: '#C7C8C8',
    paddingHorizontal: 16,
    paddingBottom: 8,
    zIndex: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 6, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 6,
  },
  option: {
    paddingVertical: 12,
  },
  optionText: {
    fontSize: 17,
    color: 'black',
  },
  modalOptionText: {
    fontSize: 18,
    color: '#2D2D2D',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    backgroundColor: '#00000066',
  },
  modalView: {
    backgroundColor: '#F6F6F6',
    padding: 20,
    borderRadius: 10,
    width: '100%',
    flex: 1,
    maxHeight: '90%',
  },
  searchBar: {
    width: '100%',
    backgroundColor: '#E7E7E8',
    height: 40,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingLeft: 16,
    marginVertical: 15,
    flexDirection: 'row',
    alignItems: 'center'
  },
  subtitle: {
    color: '#3C3C4399',
    fontSize: 13
  },
  addButton: {
    borderRadius: 20,
    padding: 8,
    paddingHorizontal: 14,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#378461',
    shadowColor: '#000',
    shadowOffset: { width: 6, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 4,
  },
  textAdd: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  selectButton: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    padding: 8,
    paddingHorizontal: 14,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 6, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 4,
  },
  textSelect: {
    fontSize: 14,
    color: '#3C3C4399',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  buttons: {
    flexDirection: 'row',
    gap: 10
  },
});

export default styles;
