platform :ios, '12.0'

target 'realspace3' do
  # Inclui as dependências do React Native
  config = use_react_native!(
    :path => '../node_modules/react-native',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Defina as dependências aqui
  pod 'Firebase/Core', '~> 10.0'  # Ajuste a versão conforme necessário
  pod 'Firebase/Auth', '~> 10.0'  # Ajuste a versão conforme necessário
  pod 'GoogleUtilities', '~> 8.0'  # Ajuste a versão conforme necessário
  pod 'FirebaseCoreInternal', '~> 10.0'  # Ajuste a versão conforme necessário

  target 'realspace3Tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
  end
end
