platform :ios, '12.0'

target 'realspace3' do
  require_relative '../node_modules/react-native/scripts/react_native_pods'
  config = use_native_modules!

  # Define dependencies here
  pod 'Firebase/Core', '~> 10.0'
  pod 'Firebase/Auth', '~> 10.0'
  pod 'GoogleUtilities', '~> 8.0'
  pod 'FirebaseCoreInternal', '~> 10.0'

  target 'realspace3Tests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer, :mac_catalyst_enabled => false)
  end
end
